### ISSUE TITLE
The navigation is buggered on mobile

### ISSUE THREAD

**Issue by sunscreem** [AberdeenPHP/AberdeenPHP-Website#10]
On small devices anyway. Will sort asap.

**Comment by dannyockilson** [comment]
The PR I had set up should have fixed the mobile menu... It doesn't seem to have taken effect though will check.

**Comment by dannyockilson** [comment]
Seems the app.css is out of sync with the changes to the scss files. Tried running the build but getting some cray-cray errors from mix-webpack. Possibly some clashing dependencies since it's using an older beta version of webpack... will debug it when I cba :p

**Comment by sunscreem** [comment]
Ah - yeah - on laravel the app.css is nearly always generated. Plus I've turned on versioning to prevent confusion when pushing live. 

I'll go and look at the PR I merged and apply the changes to the scss version.

**Comment by sunscreem** [comment]
Balls - this is confusing. I think I got a conflict, locally, when I first merge your change in danny. And them mistakenly removed the wrong one. 

I saw this because I applied the change on develop, all working, then went to merge and got the conflict again. Only time i've had conflict like that in the past was litterally when me and billy changed the same file. 

Anyway - its fixed now. Couple of changes though. The class you were applying the fix to needed changed and the colour you chosen ment it was black text on a dark background? Let me know if I've buggered it up - if not - can you close this issue?

**Comment by dannyockilson** [comment]
Yeah that's fine :)

I had put black background and white text but the other way round works fine as well 👍
