### ISSUE TITLE
Other events in Aberdeen

### ISSUE THREAD

**Issue by dannyockilson** [AberdeenPHP/AberdeenPHP-Website#13]
This bit is nice but having it at the bottom of our events makes it a lot of scrolling. Would people be ok with me moving this over to the community page?

**Comment by sunscreem** [comment]
That make sense to me. Either that or we collapse the details of the existing events?

**Comment by sunscreem** [comment]
(Are you about to get your hands dirty in laravel lol?)

**Comment by dannyockilson** [comment]
Yeah I'm gonna sort it tomorrow :)

**Comment by dannyockilson** [comment]
#15 should do this, still a few tweaks on going but think it's pretty much good to go :)
