### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by sunscreem** [AberdeenPHP/AberdeenPHP-Website#14]
Any reason I can't add a contact form? 

Is the info@aberdeenphp.co.uk all working okay Danny?

I'll need you to add some DNS records for mailgun if you are happy to @dannywilson.

**Comment by dannyockilson** [comment]
We can do yeah. I only ever got spam through it on the old site so not overly missing it but can't hurt to add one on.

**Comment by sunscreem** [comment]
Cool - I'll do that today. If I can be arsed. Probably not. The sun is out.

**Comment by sunscreem** [comment]
Danny can add the following subdomain to abphp so we can send outgoing email via mailgun (I'll cover the cost - not that it will be anything other than pennies)? 

`mg.aberdeenphp.co.uk` with the following entries:

- [ ] Type: `TXT` Hostname: `mg.aberdeenphp.co.uk` Value: `v=spf1 include:mailgun.org ~all`

- [ ] Type: 'TXT' Hostname: `mailo._domainkey.mg.aberdeenphp.co.uk` Value: `k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDF97QL30h787wneaMtJCqFptSSxGuWX/C8TVe34YrzmqNVkEYOGstK06RRdrqAO1AQX5ImzSOmUyDXWQvpDka0NiaCUYT/r1wSQIjzwMCL3Co7KIGRdxs0pyQ2lp6DUPyMiyTgWdanECSMVOnVJM5LkQa1aY8H49hlW0oXEgwEpQIDAQAB`

- [ ] Type: `MX` Priority: `10` Value: `mxa.mailgun.org`

- [ ] Type: `MX` Priority: `10` Value: `mxb.mailgun.org`

- [ ] Type: `CNAME` Hostname: `email.mg.aberdeenphp.co.uk` Value: `mailgun.org`

**Comment by sunscreem** [comment]
@dannywilson Can I remind you about adding those dns entries for me dude?

**Comment by sunscreem** [comment]
Oh and check this:

[Code - Markdown Email!](https://github.com/AberdeenPHP/AberdeenPHP-Website/blob/feature-addcontactform/resources/views/emails/contact-us-message.blade.php)

Produces:

![image](https://cloud.githubusercontent.com/assets/7523595/23832644/e00e0258-0730-11e7-877a-0a1ea95dd6a4.png)

Gotta love laravel (sometimes)

**Comment by dannyockilson** [comment]
Will get on the DNS this morning :)

**Comment by dannyockilson** [comment]
Updated the DNS (my definition of morning is very loose) Should tick through in a few hours (cheap hosting and ttl min is 4 hours)

**Comment by sunscreem** [comment]
No problemo. I'll keep an eye on it changing :)

**Comment by sunscreem** [comment]
@dannywilson [Still No Change Yet :(](https://toolbox.googleapps.com/apps/dig/#MX/aberdeenphp.co.uk)

**Comment by dannyockilson** [comment]
added them on the subdomain... mg.aberdeenphp.co.uk was than not the correct thing to do? https://toolbox.googleapps.com/apps/dig/#MX/mg.aberdeenphp.co.uk If they need to be on the main one I can make the changes :)

**Comment by sunscreem** [comment]
oh ffs - you did too and that is correct. Sorry man my mistake. Leave it with me.

**Comment by sunscreem** [comment]
@dannywilson You should have an email from the contact form now (assuming spam filters have let it through). Add a new issue if you want me to add the invisible recaptcha if you think it needs it  :)
