### ISSUE TITLE
Are we okay to use the background images?

### ISSUE THREAD

**Issue by sunscreem** [AberdeenPHP/AberdeenPHP-Website#17]
Random thought...

https://www.flickr.com/photos/29609591@N08/5371187508/

If this is the source of this one it's under copyright. 

Same with this one I think..

http://www.panoramio.com/photo/40588614

**Comment by billythekid** [comment]
we should use them under whatever terms the licences have, attribute etc.

- Dunnottar castle isn't even in aberdeen

**Comment by AndyGaskell** [comment]
In practice I just used the ones I'd used on my website, though took out the ones about joomla or my work.  I have the same large header that loads randomly sort of thing there. If you go to...
http://ssofb.co.uk/contact-us
....and hit F5 a few times, you'll see a few of them.

They're really just meant as eye candy placeholders, it'd be great if we could replace them with ones that were more 'us' or ones that are CC licensed.  It's a bit more tricky as the images are very wide, ideally 1600x400 so a lot of snaps don't really fit that.  I think it's harder as we're often indoors and only have phones on us, so collectively don't have great photos of meetings etc.

I know Dunnottar castle isn't in Aberdeen, but it's nearby, and it looks nice :) most of us don't actually live in Aberdeen city, so it's not like we're a city only gig.

I took a pic yesterday that might be ok, though it's a phone & indoor shot, so not so sharp, but might be good enough.
![stag_1600x400](https://cloud.githubusercontent.com/assets/91541/23990239/56914d96-0a2d-11e7-9e80-fe5296259e8a.jpg)

**Comment by billythekid** [comment]
that pics good because it has girls in it, showing how diverse literally
EVERY meeting is.

**Comment by sunscreem** [comment]
I like that pic - dunno if it says "clique" though?

**Comment by sunscreem** [comment]
Just spoke with Chris (notnixon).... 

He's going to sort us out with a few pics to choose from. All along the same lines as the current ones ☺️

**Comment by sunscreem** [comment]
Danny. How would you feel about giving Chris a wee link on the supporters bit if we use his images?

**Comment by caleuanhopkins** [comment]
Can we not reach out to a few photographers on Flickr that have CC license and just credit them with a small `<caption>` in the banner's bottom right corner?

**Comment by sunscreem** [comment]
I'd prefer it to come from someone we know if we can?

**Comment by caleuanhopkins** [comment]
@sunscreem 6 and two 3s. We'd probably be putting Chris' credit on the photos anyway so we could mix and match if we feel we need more

**Comment by sunscreem** [comment]
Here we go folks. 

Chris just sent over this. All pre cropped for us too. 

What do we think. Any of these any use? 

https://drive.google.com/folderview?id=0B-_K4N3k8CHraXlGV1ZiN3oxTmc

**Comment by caleuanhopkins** [comment]
7,5,4 and 6 are all good for me. the others I could take or leave. Generally, though, they will do nicely. Though if we could get some birds eye replacements for the ones we have on the site, I think that would look good too mixed in with these

**Comment by AndyGaskell** [comment]
They all look great, nice one :) 

I would say, just drop all 7 of therm into the "public/images/random_header_images/" and see how they look on the site.  The images feel look different in place, and will vary quite a lot depending on device / viewport.

Then we'll have 17, which is a good number, folk wont often see repeats.  From there we can just hive off the least good ones.  My general feeling is most of these are better than most of the ones we have, that said, I'm a sucker for aerial photos.

**Comment by sunscreem** [comment]
I'll do this tomorrow ☺️

I'll need to remove any of the copyrighten images though. Any ideas if any of the original ones are okay for us to use?

**Comment by AndyGaskell** [comment]
Not sure re copyright ones, some were, I think CC, but not sure which.  I'm sure it's probably not really a problem, and if it arises, just forward any lawyers letter to me ;)

**Comment by sunscreem** [comment]
Cool - I've a lot of worry about using other folks pics without express permission Andy. I've been stung in the past with a american company sending me a huge cease and desist. I'm maybe being over cautious.

@dannywilson Can you take a deciding vote?

**Comment by billythekid** [comment]
Just looked at Chris's pictures, they're excellent. I'd be happy with any of those. I like what Andy suggests and just have it randomly take one.
