### ISSUE TITLE
Change logo back to svg

### ISSUE THREAD

**Issue by sunscreem** [AberdeenPHP/AberdeenPHP-Website#19]

**Comment by caleuanhopkins** [comment]
because for some reason Github won't let me upload SVG files:
[ab-php-logo.svg.zip](https://github.com/AberdeenPHP/AberdeenPHP-Website/files/845559/ab-php-logo.svg.zip)

Change elephant to match PHP elephant and changed font Open San to match website. Can send .ai file if anyone needs it

**Comment by sunscreem** [comment]
Thanks Callum. I'm not up to speed with svg so I might need to come back to you on this one. I should have this done tomorrow or Friday.

**Comment by caleuanhopkins** [comment]
@sunscreem aye no probs, any issues I can implement it in like a few seconds.

@dannywilson make sure you approve the slight changes to the logo b4 we go too far into implementing it

**Comment by billythekid** [comment]
i approve

**Comment by sunscreem** [comment]
Proper lol!

**Comment by dannyockilson** [comment]
I've pushed up a PR with the svg in place, just stuck the original file with the fonts converted to outlines. This means we don't have to load the fonts for it to render properly (also it's a typekit font and typekit is SLOW AS HELL sometimes so best to avoid relying on it)

**Comment by caleuanhopkins** [comment]
apologies haven't exploded out the fonts when I did last night. Here's an updated version with ungrouped layers and objects instead of a font. it's compressed too and should be "responsive", whatever that means in illustrator.

[ab-php.svg.zip](https://github.com/AberdeenPHP/AberdeenPHP-Website/files/847067/ab-php.svg.zip)

**Comment by sunscreem** [comment]
@AndyGaskell Did you see there's an updated version that needs added to that PR?

**Comment by dannyockilson** [comment]
Ah didn't realise you'd done that, did the same thing to it before uploading the PR ;)

**Comment by sunscreem** [comment]
Callum. Any browsers that we should be double checking this in?

**Comment by caleuanhopkins** [comment]
@sunscreem nope, if we're sticking with the recommended list of support browsers [IE](https://en.wikipedia.org/wiki/Internet_Explorer_version_history#Release_history_for_desktop_Windows_OS_version), [FF](https://en.wikipedia.org/wiki/Firefox_version_history#Release_history), [Chrome](https://en.wikipedia.org/wiki/Google_Chrome_version_history), [Safari](https://en.wikipedia.org/wiki/Safari_version_history#Version_compatibility), [Edge](https://en.wikipedia.org/wiki/Microsoft_Edge#Release_history). Opera Mini still supports sweet FA but SVG should be treated as code standard now that Microsoft have dropped old browser support

**Comment by sunscreem** [comment]
That's me tested in chrome, firefox, android web thingy, on an iphone 5 and edge on windows 10 and the logo looks fine on them all. Closing - ta for you help on this one danny + callum :)

**Comment by dannyockilson** [comment]
Hey just reopening this quickly. Should I be using the new design for social media and stuff to keep consistent? (I know the logo is fairly small on the site so people might not actually notice they're different :p)

**Comment by sunscreem** [comment]
I would say so Danny. I'll need to update it on my news site too. (If I'm honestly I never noticed a difference?)

**Comment by caleuanhopkins** [comment]
I also want royalties. 

🍕+🍺
