### ISSUE TITLE
Website Amendments From Rowan

### ISSUE THREAD

**Issue by sunscreem** [AberdeenPHP/AberdeenPHP-Website#25]
## Site Wide  

- [x] Body text needs normal font (sans serif ? Match what's used isn't the banners and nav)
Justify text ?

## Home
- [x] Change location and time to list/field with map
- [x] "We usually have pizza, beer and soft drinks."  - remove usually (provide? ). Add tea and coffee / hot drinks
- [x] "The group is a diverse," remove 'a' 

## About
- [x] Title - Remove full stop 
- [x] Title - capitalise Background
- [x] Content - after first sentence, say what it stands for cos everyone asks.
- [x] Content - "The group is a diverse, " new paragraph.
- [x] Content - insert full width picture with a pile of the people, or shot that captures the setup in the room
- [x] Photos - edit so not so dull
- [x] Photos - picture viewer so when you click you see a big one
- [x] Photos - increase bottom margin to drop text a little
- [x] Photos - two pictures just has the letters tbc instead of a pic

## Events
- [x] Bday event - more content on the fact it's a celebration.
- [x] Google maps- it opens the app on the iPad and goes to the area but doesn't highlight the pin
- [x] Feature - month view calendar
- [x] Add the bit at the end 'Events from OpenTechCalendar.' At the top too
- [x] Feature - logo thumbnails

## Talks

- [x] "Get in touch via..." never multiple periods
- [x] Add email and twitter icon before their info
- [x] Add photo of a talk happening
- [x] Add list of some previous talks (any links to talker and slides)

## Community
- [x] "This page is for info" say information.

# Tech community
- [x] Make the links underline to show they are links. (On whole page).
- [x]  Add info on when they occur.
- [x] Add photo

## Contact
- [x] Make send look like a button
- [x] "Your details will never be shared." - make shared a link to privacy
- [x] "You can use the form here or any of these methods:" remove

## Code of Conduct
- [x] Title  type COnduct
- [x] "help ensuring a safe environment for all involved." Ensure ?
- [x] Contact list - don't use a dash
- [x] Contact list - bigger line spacing 

## Privacy 
- [x] "	•	whenever you are asked to fill in a form on the website, look for the box that you can click to indicate that you do not want the information to be used by anybody for direct marketing purposes"  there's no box on the contact form
- [x] "writing to or emailing us." There's an address to write to ?

## T&cs
- [x] "	•	You may not create a link to this website from another website or document without AberdeenPHP’s prior written consent.
" eh?

**Comment by sunscreem** [comment]
I'm happy to work through these and get the changes done, but if anyone else wants to help out that would be great.

@zenrhe I just cut and paste your list you emailed as they all make sense to me :)

**Comment by dannyockilson** [comment]
Will grab a few tomorrow :) If anyone else is wanting to just make sure you tick them off :)

**Comment by sunscreem** [comment]
Plenty more to do. I've done the easy ones for now :)

**Comment by sunscreem** [comment]
That's nearly all of these done. Some of the items need a little more discussion. I'll raise them as separate issues.
