### ISSUE TITLE
ReadMe needs updating

### ISSUE THREAD

**Issue by billythekid** [AberdeenPHP/AberdeenPHP-Website#26]
The intro to laravel routes could do with an update, we're not using callback functions in the routes/web.php file anymore we're using controllers so all the blurb in the readme about returnign a view isn't very helpful and will only confuse folks. 

Perhaps it might be a good idea to put an example callback one in there for people to contribute with, that we can pull into the MVC setup later. Then the readme can say somthing like, "just copy the example block at the top of the file to add your page, changing these values..."?

**Comment by sunscreem** [comment]
Agreed with both sir. I'll sort this soon.
