### ISSUE TITLE
OpenTechCal Timeout Issues

### ISSUE THREAD

**Issue by sunscreem** [AberdeenPHP/AberdeenPHP-Website#27]
No need to comment or jump on fixing this, just to make you all aware that I've now had a few bug reports because of opentechcal having issues with their API.

```
file_get_contents(https://opentechcalendar.co.uk/api1/group/272/events.json): failed to open stream: Connection timed out
```
The code that [does this pull is here](https://github.com/AberdeenPHP/AberdeenPHP-Website/blob/master/app/Http/Controllers/EventsPagesController.php#L15).

This is just the age old problem of relying on third parties for content and the solution is to pull a copy in to our own database on a schedule. I'll keep an eye on it and if it continues to happen I'll do the codez to fix it.

@dannywilson Can you close this issue once you've seen it dude?

**Comment by dannyockilson** [comment]
Yeah, the caching should be enough for this? We can set the cache to refresh weekly or something? The other option would be to do the call on the frontend (least we can show an error/loader that way?)

**Comment by sunscreem** [comment]
I'm not sure. Caching for longer than longer still kinda feels like a bit a workaround to me, and doesn't really solve the problem of if they are down for any reason.  Doing the call on the front end is an option but I'd worry that someone could screw us up and get us blocked somehow.

**Comment by billythekid** [comment]
What's the report? how does it fail? can't this just be wrapped in a
try/catch like everything else?

**Comment by dannyockilson** [comment]
Frontend should be pretty safe since it's just an ical feed (read only) but yeah storing them somewhere as a backup make sense. I'm not sure what Laravel uses for Caching out the box but I'd consider cache vs storage in a db relatively equivocal? I don't see how it is any less robust (in terms of dealing with service outage). The other alternative is we just pull the icals into a google calendar and use that as a proxy, google will auto-update from the ical intermittently and is a little less likely to suffer outages.

**Comment by sunscreem** [comment]
I'm just using a the built in file cache that ships with Laravel.

I think there is a difference between the two approaches (caching verses db) let me explain my thinking as I'm probably wrong lol.

Let say OpenTechCal is down for whatever reason:

Cache; There's been no visitors to the site for a day so the cache is empty (if it remains set at 2 hours like now). It tries to pull a fresh update, fails and so our visitor will get a 500.

DB; If we are using a DB to make a copy, then our task runs to start the update, spots that opentechcal is down so leaves our current copy intact and the visitor sees the last good details.

Am I thinking right?

**Comment by dannyockilson** [comment]
Yeah that makes sense I just figured we'd bump up the cache length significantly (the data doesn't change overly regularly). Could we also pre-fill the cache using the scheduler? Or could do a

```
try {
 // Make request
// update cache
} catch(e) {
 // load from cache
}
```

style thing and set the cache lifetime to a few thousand years :p

**Comment by sunscreem** [comment]
That's an interesting angle. I've always worked on the idea that once the cache expires then that's it. Let me have a look into that one and see if laravel has some clever stuff built in for handling this. Can't begin to tell you the number of times I've found a one line solution for stuff like that.

**Comment by sunscreem** [comment]
Closing as we've had zero error on this for months.
