### ISSUE TITLE
Rowan suggested changing the body text to match the header

### ISSUE THREAD

**Issue by sunscreem** [AberdeenPHP/AberdeenPHP-Website#40]
Rowan wrote:

_Body text needs normal font (sans serif ? Match what's used isn't the banners and nav)_

_Justify text ?_

I'm guessing the font choice was part of the theme @AndyGaskell used? My personal opinion is keep it as is. Anyone disagree?

**Comment by AndyGaskell** [comment]
Yea, I'm not sure if there is really a right answer tbh.

I used to use Sans everywhere, but last few years I switched to sans for headings and serif for body, which is supposed to be better for readability.  There is pretty established research on serif fonts being easier to consume in long-form reading.

**Comment by sunscreem** [comment]
CLosing for now. We can always re-open if anyone comments the same.
