### ISSUE TITLE
Rowans comments on "About Us" photos

### ISSUE THREAD

**Issue by sunscreem** [AberdeenPHP/AberdeenPHP-Website#41]
Rowan wrote:

_edit so not so dull_
_picture viewer so when you click you see a big one_

Anyone fancy picking this one up? I have a hatred of building picture viewers.

If no-one wants too I'll need original photos from Andy (if you could crop them to something sensible -
 say 800px wide and upload them in PR @AndyGaskell that would be great!). I'll then use [Featherlight.js](http://noelboss.github.io/featherlight/) unless anyone has an alternative lightbox they prefer?

**Comment by AndyGaskell** [comment]
I don't mind doing this, I'd kind of held off in-case there was a lavavel-ey way of doing it.

I think the template includes Cleverbox or Fancybox, from memory.

I think, from memory, the images are (or were) quite large, so we will probably have higher res ones.

@sunscreem let me know here if you wanna to do this, otherwise I'll have a go

**Comment by sunscreem** [comment]
Ach. If you can process the large photos to a uniform(ish) size and maybe
brighten the existing small images a bit that would save me the bit I hate
doing?

**Comment by billythekid** [comment]
I'd quite like to build a lightbox. You know how I like javascriptz

**Comment by sunscreem** [comment]
Fill. Your. Boots.

**Comment by AndyGaskell** [comment]
ok, sounds a plan, @billythekid you do the JS and I'll sort out the images :)

**Comment by AndyGaskell** [comment]
So, the images themselves are all 600px wide, so we can probably just use the same ones inline as in the lightbox, at least to start with.

**Comment by billythekid** [comment]
I've thrown something together in the btkLightbox branch. Stupidly simple, raw JS and SCSS. Feel free to screw with it. Completely untested in anything other than chrome on my mac. ymmv etc.

**Comment by sunscreem** [comment]
Cheers for that Billy.

It could defo do with some additions - ability to swipe through (and cursor keys) through image, better mobile implementation, close on esc, stretch images if they are a little small, captions, etc but you know what... You wrote this from scratch in vanilla JS and for that, sir, I tip my hat. It'll do the job nicely.
