### ISSUE TITLE
Huge weirdness going on with AB PHP website?

### ISSUE THREAD

**Issue by sunscreem** [AberdeenPHP/AberdeenPHP-Website#45]
Last week I had to disable the uptime monitoring on the website as it saying it was down a lot when it definately wasn't. I assumed it was a DNS issue, so, as Danny was away I shelved it for a couple of days as "one of those weird things".

Now yesterday I've got a HUGE list of broken urls being reported by webmaster tools.

None of the urls have ever existed on this server and there's no site map or anything to confuse matters.

Here's the list.

https://docs.google.com/spreadsheets/d/1VtQ2yvMhU-rcl5lUu3AVserh6Ezly5HKh-D7RPtqUWM/edit?usp=sharing

@dannywilson Any of this look familiar? 

Only other thing I can think it something weird happened with pulling in the events?

Anyone able to help me work this one out?

**Comment by AndyGaskell** [comment]
The...

> Now yesterday I've got a HUGE list of broken urls being reported by webmaster tools.

...looks like inbound spam to me.  Either inbound spam links or spam 404 bots.  I usually just ignore these.

**Comment by sunscreem** [comment]
Hmm - I've not seen that before.

**Comment by sunscreem** [comment]
@dannywilson I notice one of the error pages has your name on it. Probably just a co-incidence?

**Comment by dannyockilson** [comment]
Erm yeah looks like a whole lot of spam, some of it is the old site though, think the author/danny one is from when it was on WordPress and some of the events ones were the old WordPress urls but 90% of it seems to be spam.

**Comment by sunscreem** [comment]
Okay - nothing I can really do anything about I guess. I'll close this and turn the uptime monitoring back on and see what happens :)
