### ISSUE TITLE
"site live" checklist

### ISSUE THREAD

**Issue by sunscreem** [AberdeenPHP/AberdeenPHP-Website#5]
I've a checklist I use when I put a site live that I still need to run through for this website. Google analytics, proper 404 pages, etc.

I'll try to get that worked through in the next couple of days. 

I thought I'd leave this issue open though so y'all are aware I'm on it :)

**Comment by dannyockilson** [comment]
Had a look at this post https://philipwalton.com/articles/the-google-analytics-setup-i-use-on-every-site-i-build/ a while ago and been meaning to try some of it out. Might be a good idea to see how effective the site is/where people come from etc?

**Comment by sunscreem** [comment]
Bloody hell - that's some clever stuff he's got going on there. I guess it would be good to see more than just how many visitors there are to the site lol.

**Comment by dannyockilson** [comment]
Yeah there's a hell of a lot in there... by no means suggesting we do it all. I've very rarely gone much beyond installing the basic tag before so could be interesting to see what we can do.

**Comment by sunscreem** [comment]
Not sure if you guys verify your sites with google and bing normally but I generally do so that I get notified if something is wrong and the can't be crawled.

**Comment by sunscreem** [comment]
Sorry about that ...

![image](https://cloud.githubusercontent.com/assets/7523595/23581526/816ced3c-010d-11e7-96c2-1f3b7c14e8b6.png)

And with that i'll close this as done. If you want to do anything with the analytics danny go right ahead sir :)

**Comment by sunscreem** [comment]
FYI: I've checked over my own list for all this plus this excellent list from spatie https://github.com/spatie/checklist-going-live
