### ISSUE TITLE
FR: Styleguide

### ISSUE THREAD

**Issue by billythekid** [AberdeenPHP/AberdeenPHP-Website#60]
Can we have a styleguide for this project please, and have some build process enforce it?

**Comment by sunscreem** [comment]
I'll get Travis and style ci running on this I reckon. Psr-2.

**Comment by sunscreem** [comment]
@billythekid Can you have a look [over here](https://github.com/sunscreem/dogpubtimemachine/pull/49) at dog pub?

Its using style ci's [laravel preset](https://docs.styleci.io/presets#laravel) and only updating php - that's a limitation of the free plan.

Is that the kind of thing you were thinking of?
