### ISSUE TITLE
Contact Form and Bugsnag Issue

### ISSUE THREAD

**Issue by sunscreem** [AberdeenPHP/AberdeenPHP-Website#61]
Looks like the contact form is borked. And no error report getting to bugsnag so I'm guessing that is too.

I'll sort it.

**Comment by evocate** [comment]
Working locally for me.

**Comment by sunscreem** [comment]
Same. Meh - will sort tomorrow. Beer taking priority just now.

**Comment by evocate** [comment]
I was going to write some tests for the contact form anyway.

**Comment by sunscreem** [comment]
Cool - if you get a min go for it. I'll get travis ci set up tomorrow to
run them on PR's.

**Comment by sunscreem** [comment]
Mailgun wasn't configured in the .env - so @dannyockilson that could be many many months you've not been getting email. Bugsnag wasn't alerting us to errors because we missed the changed need in 5.5/5.6.

You'll probably get a ton of spam now. Let me know if you want recaptcha added.
