### ISSUE TITLE
Merge the news website into this website. 

### ISSUE THREAD

**Issue by sunscreem** [AberdeenPHP/AberdeenPHP-Website#8]
I can't see any good reason to have the news as a separate site.

I'll make sure the url (news.aberdeenphp.co.uk) still works, but I think I'll get the new to match the theme of the new website and move forward from there.

Give me a comment if that doesn't seem sensible to you.

**Comment by sunscreem** [comment]
I'm now leaning towards keeping this separate as I can see the news site getting a bit more complex and probably just making contributing to the abphp site even more challenging for noobs.

**Comment by caleuanhopkins** [comment]
👍

does that mean I'm a contributor now?
